// @ts-expect-error `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
import { default as handler } from "./.open-next/worker.js";

/**
 * Cron Triggers call the same admin routes the Vercel crons used, through the
 * generated Next fetch handler, authenticated with CRON_SECRET. Schedules are
 * declared in wrangler.jsonc `triggers.crons` and matched here by expression.
 */
const CRON_ROUTES: Record<string, string> = {
  "0 4 * * *": "/api/admin/gc",
  "15 * * * *": "/api/admin/embed-sweep",
};

export default {
  fetch: handler.fetch,

  async scheduled(event, env, ctx) {
    const path = CRON_ROUTES[event.cron];
    if (!path) {
      console.error(`no route for cron ${event.cron}`);
      return;
    }
    const request = new Request(`https://cron.internal${path}`, {
      headers: { authorization: `Bearer ${env.CRON_SECRET}` },
    });
    const response = await handler.fetch(request, env, ctx);
    if (!response.ok) {
      console.error(`cron ${path} failed: ${response.status} ${await response.text()}`);
    }
  },
} satisfies ExportedHandler<CloudflareEnv>;
